/*
 * Progaramming Priciples 01 (Course Work - 2 )
 * Student Name - Dilum Maduranga De Silva
 * UoW ID       - 16266371 (W1626637)
 * IIT ID       - 2016142  
 */
package HangManGame;


import java.util.*;
import javax.swing.*;


/**
 *
 * @author Dilum De Silva
 */
public class HangManGame extends javax.swing.JFrame {

    private int rightLetter;
    private String hiddenWord;
    private int wrongLetter;
    
    //create a word array to store the words
    String[] words = {"september", "institute", "education", "chemistry", "resources", "different"};
    

    /**
     * Creates new form HangManGame
     */
    public HangManGame() {
        initComponents();
        
         gameoverlbl.setVisible(false);
            mkeydead.setVisible( false );
             lionsadlbl.setVisible(false);
                beforehang1.setVisible(false);
                  deadfacelbl.setVisible(false);
                    deadbodylbl.setVisible(false);
                     boyandbearhappy.setVisible(false);
                        loseback.setVisible(false);
                          cloud2.setVisible(false);
                        clouds1.setVisible(false);
                     ltrABC.setVisible(false);
                    happy7tiger.setVisible(false);
                    boy2.setVisible(false);
                 boy3.setVisible(false); 
                snakelbl.setVisible(false);
              mkey1.setVisible(false);
             mkey2.setVisible( false );
         happy6.setVisible(false);   
         
        hiddenWord = getRandom(words);
        System.out.println(hiddenWord);
        
    }

    HangManGame(Object object, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Hmanworkspace = new javax.swing.JPanel();
        cloud2 = new javax.swing.JLabel();
        clouds1 = new javax.swing.JLabel();
        loseback = new javax.swing.JLabel();
        char1 = new javax.swing.JLabel();
        ltrABC = new javax.swing.JLabel();
        char2 = new javax.swing.JLabel();
        char3 = new javax.swing.JLabel();
        char4 = new javax.swing.JLabel();
        char5 = new javax.swing.JLabel();
        char6 = new javax.swing.JLabel();
        char7 = new javax.swing.JLabel();
        char8 = new javax.swing.JLabel();
        char9 = new javax.swing.JLabel();
        char10 = new javax.swing.JLabel();
        inputLetter = new javax.swing.JTextField();
        boyandbearhappy = new javax.swing.JLabel();
        happy6 = new javax.swing.JLabel();
        happy7tiger = new javax.swing.JLabel();
        wrongGuesses = new javax.swing.JLabel();
        tryLetter = new javax.swing.JButton();
        gameoverlbl = new javax.swing.JLabel();
        cloudlbl02 = new javax.swing.JLabel();
        cloudlbl01 = new javax.swing.JLabel();
        atmptBIrdlbl = new javax.swing.JLabel();
        enteraltrlbl = new javax.swing.JLabel();
        mkeydead = new javax.swing.JLabel();
        boardlbl = new javax.swing.JLabel();
        mkey1 = new javax.swing.JLabel();
        mkey2 = new javax.swing.JLabel();
        lionsadlbl = new javax.swing.JLabel();
        boy1 = new javax.swing.JLabel();
        mkeymid = new javax.swing.JLabel();
        boy2 = new javax.swing.JLabel();
        boy3 = new javax.swing.JLabel();
        deadfacelbl = new javax.swing.JLabel();
        deadbodylbl = new javax.swing.JLabel();
        beforehang1 = new javax.swing.JLabel();
        hangtool = new javax.swing.JLabel();
        snakelbl = new javax.swing.JLabel();
        workspacelbl = new javax.swing.JLabel();
        hangPicture = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1204, 698));
        setMinimumSize(new java.awt.Dimension(1204, 698));
        setPreferredSize(new java.awt.Dimension(1204, 698));
        setResizable(false);
        setSize(new java.awt.Dimension(1204, 698));
        getContentPane().setLayout(null);

        Hmanworkspace.setPreferredSize(new java.awt.Dimension(1208, 698));
        Hmanworkspace.setLayout(null);

        cloud2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangManGame/cloud2.png"))); // NOI18N
        Hmanworkspace.add(cloud2);
        cloud2.setBounds(690, 10, 430, 230);

        clouds1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangManGame/clouds1.png"))); // NOI18N
        Hmanworkspace.add(clouds1);
        clouds1.setBounds(480, -10, 500, 278);

        loseback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangManGame/rsz_lose1.png"))); // NOI18N
        loseback.setMaximumSize(new java.awt.Dimension(1200, 674));
        loseback.setMinimumSize(new java.awt.Dimension(1200, 674));
        loseback.setPreferredSize(new java.awt.Dimension(1200, 674));
        Hmanworkspace.add(loseback);
        loseback.setBounds(0, -150, 1680, 970);

        char1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        char1.setText("X");
        Hmanworkspace.add(char1);
        char1.setBounds(690, 80, 40, 50);

        ltrABC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ltrABC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangManGame/winltr.png"))); // NOI18N
        Hmanworkspace.add(ltrABC);
        ltrABC.setBounds(900, 510, 230, 160);

        char2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        char2.setText("X");
        Hmanworkspace.add(char2);
        char2.setBounds(720, 90, 20, 30);

        char3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        char3.setText("X");
        Hmanworkspace.add(char3);
        char3.setBounds(750, 90, 30, 30);

        char4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        char4.setText("X");
        Hmanworkspace.add(char4);
        char4.setBounds(780, 90, 30, 30);

        char5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        char5.setText("X");
        Hmanworkspace.add(char5);
        char5.setBounds(810, 90, 20, 29);

        char6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        char6.setText("X");
        Hmanworkspace.add(char6);
        char6.setBounds(840, 90, 30, 30);

        char7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        char7.setText("X");
        Hmanworkspace.add(char7);
        char7.setBounds(870, 90, 20, 30);

        char8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        char8.setText("X");
        Hmanworkspace.add(char8);
        char8.setBounds(900, 90, 30, 30);

        char9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        char9.setText("X");
        Hmanworkspace.add(char9);
        char9.setBounds(930, 90, 20, 30);

        char10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        char10.setText("X");
        Hmanworkspace.add(char10);
        char10.setBounds(960, 90, 16, 30);

        inputLetter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputLetterActionPerformed(evt);
            }
        });
        Hmanworkspace.add(inputLetter);
        inputLetter.setBounds(900, 430, 190, 30);

        boyandbearhappy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boyandbearhappy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangManGame/mdhappy4.png"))); // NOI18N
        Hmanworkspace.add(boyandbearhappy);
        boyandbearhappy.setBounds(310, 400, 410, 310);

        happy6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangManGame/mdhappy1.png"))); // NOI18N
        Hmanworkspace.add(happy6);
        happy6.setBounds(440, 460, 210, 210);

        happy7tiger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangManGame/mdhappy2.png"))); // NOI18N
        Hmanworkspace.add(happy7tiger);
        happy7tiger.setBounds(690, 480, 236, 190);

        wrongGuesses.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        wrongGuesses.setText("0");
        Hmanworkspace.add(wrongGuesses);
        wrongGuesses.setBounds(880, 180, 70, 60);

        tryLetter.setBackground(new java.awt.Color(204, 204, 204));
        tryLetter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tryLetter.setText("Try letter");
        tryLetter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tryLetterActionPerformed(evt);
            }
        });
        Hmanworkspace.add(tryLetter);
        tryLetter.setBounds(940, 470, 100, 30);

        gameoverlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangManGame/GameOver1.png"))); // NOI18N
        Hmanworkspace.add(gameoverlbl);
        gameoverlbl.setBounds(720, 330, 420, 220);

        cloudlbl02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangManGame/cloud2.png"))); // NOI18N
        Hmanworkspace.add(cloudlbl02);
        cloudlbl02.setBounds(590, -10, 450, 210);

        cloudlbl01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangManGame/clouds1.png"))); // NOI18N
        Hmanworkspace.add(cloudlbl01);
        cloudlbl01.setBounds(780, 0, 380, 130);

        atmptBIrdlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangManGame/attempt3.png"))); // NOI18N
        atmptBIrdlbl.setText("jLabel1");
        Hmanworkspace.add(atmptBIrdlbl);
        atmptBIrdlbl.setBounds(760, 110, 260, 290);

        enteraltrlbl.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        enteraltrlbl.setForeground(new java.awt.Color(255, 255, 255));
        enteraltrlbl.setText("Enter a letter");
        Hmanworkspace.add(enteraltrlbl);
        enteraltrlbl.setBounds(930, 390, 150, 30);

        mkeydead.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mkeydead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangManGame/mkeydead1.png"))); // NOI18N
        Hmanworkspace.add(mkeydead);
        mkeydead.setBounds(950, 530, 150, 140);

        boardlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangManGame/rsz_1board.png"))); // NOI18N
        boardlbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Hmanworkspace.add(boardlbl);
        boardlbl.setBounds(730, 320, 470, 660);

        mkey1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangManGame/rsz_hcut.png"))); // NOI18N
        Hmanworkspace.add(mkey1);
        mkey1.setBounds(310, 410, 170, 120);

        mkey2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mkey2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangManGame/mkey2.png"))); // NOI18N
        Hmanworkspace.add(mkey2);
        mkey2.setBounds(290, 160, 130, 180);

        lionsadlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lionsadlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangManGame/lionsad3.png"))); // NOI18N
        Hmanworkspace.add(lionsadlbl);
        lionsadlbl.setBounds(610, 510, 220, 140);

        boy1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boy1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangManGame/boy75.png"))); // NOI18N
        Hmanworkspace.add(boy1);
        boy1.setBounds(720, 550, 70, 140);

        mkeymid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mkeymid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangManGame/rsz_hcut.png"))); // NOI18N
        Hmanworkspace.add(mkeymid);
        mkeymid.setBounds(240, 250, 247, 255);

        boy2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boy2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangManGame/boy50.png"))); // NOI18N
        Hmanworkspace.add(boy2);
        boy2.setBounds(670, 510, 120, 260);

        boy3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boy3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangManGame/boy25.png"))); // NOI18N
        Hmanworkspace.add(boy3);
        boy3.setBounds(550, 480, 270, 350);

        deadfacelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deadfacelbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangManGame/dead face.png"))); // NOI18N
        Hmanworkspace.add(deadfacelbl);
        deadfacelbl.setBounds(130, 350, 90, 100);

        deadbodylbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deadbodylbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangManGame/deadbody2.png"))); // NOI18N
        Hmanworkspace.add(deadbodylbl);
        deadbodylbl.setBounds(120, 370, 130, 180);

        beforehang1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangManGame/beforehang.png"))); // NOI18N
        Hmanworkspace.add(beforehang1);
        beforehang1.setBounds(300, 480, 240, 220);

        hangtool.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hangtool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangManGame/rsz_100pct.png"))); // NOI18N
        Hmanworkspace.add(hangtool);
        hangtool.setBounds(30, 300, 490, 370);

        snakelbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        snakelbl.setIcon(new javax.swing.ImageIcon("F:\\HangMan(My)\\Hangman pics\\snakecut.png")); // NOI18N
        Hmanworkspace.add(snakelbl);
        snakelbl.setBounds(-30, 0, 570, 330);

        workspacelbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangManGame/back25%.jpg"))); // NOI18N
        workspacelbl.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Hmanworkspace.add(workspacelbl);
        workspacelbl.setBounds(0, 0, 1680, 970);
        workspacelbl.getAccessibleContext().setAccessibleParent(this);

        hangPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangManGame/hang1.png"))); // NOI18N
        hangPicture.setBorderPainted(false);
        hangPicture.setContentAreaFilled(false);
        Hmanworkspace.add(hangPicture);
        hangPicture.setBounds(570, 160, 150, 110);

        getContentPane().add(Hmanworkspace);
        Hmanworkspace.setBounds(0, -1, 1200, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tryLetterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tryLetterActionPerformed
        char[] wordCharList = hiddenWord.toCharArray();
        String getLetter = inputLetter.getText().toLowerCase();

        int wrongcount = 0;
        for (int i = 0; i < wordCharList.length; i++) {
            if (wordCharList[i] == getLetter.charAt(0)) {
                switch (i) {
                    
                    case 0:
                    char1.setText(getLetter);
                    break;
                    
                        case 1:
                        char2.setText(getLetter);
                        break;
                    
                            case 2:
                            char3.setText(getLetter);
                            break;
                    
                                case 3:
                                char4.setText(getLetter);
                                break;
                    
                                    case 4:
                                    hangtool.setVisible(false);    
                                    char5.setText(getLetter);
                                    break;
                    
                                    case 5:
                                    ltrABC.setVisible(true);
                                    char6.setText(getLetter);
                                    break;
                    
                                case 6:
                                happy6.setVisible(true);
                                char7.setText(getLetter);
                                break;
                    
                            case 7:
                            happy6.setVisible(false);
                            happy7tiger.setVisible(true);
                            boy1.setVisible( false ); 
                            char8.setText(getLetter);
                            break;
                    
                        case 8:
                        happy7tiger.setVisible(false);
                        boyandbearhappy.setVisible(true);
                        char9.setText(getLetter);
                        break;
                    
                    case 9:
                    char10.setText(getLetter);
                    inputLetter.setVisible( false );
                    Hmanworkspace.remove(tryLetter);      
                    enteraltrlbl.setVisible( false );
                    break;
                    
                  default:
                  break;
                    
                  
                    
                }

                rightLetter++;
            } else {
                wrongcount++;
            }
        }
        if (wrongcount == wordCharList.length) {
            wrongcount = 0;
            wrongLetter++;
            wrongGuesses.setText(Integer.toString(wrongLetter));

        }
        inputLetter.setText(null);
        if (rightLetter == wordCharList.length) {
             boy1.setVisible( false ); 
            dispose(); 
            winJframe winpage=new  winJframe();
            winpage.setVisible(true);
              //put what you want to happen when you win the game
            

        }
        switch (wrongLetter) {
            case 1:
            hangtool.setVisible(true);  
            happy6.setVisible(false);
            happy7tiger.setVisible(false);
            boyandbearhappy.setVisible(false);
            ltrABC.setVisible(false);
            happy6.setVisible(false);
            happy7tiger.setVisible(false);
            snakelbl.setVisible(true);
            mkey1.setVisible( false );
            mkeymid.setVisible( true );
            mkeydead.setVisible( false );
           
            break;
            
            case 2:
            hangtool.setVisible(true); 
            happy7tiger.setVisible(false);
            boyandbearhappy.setVisible(false);
            ltrABC.setVisible(false);
            happy6.setVisible(false);
            mkeymid.setVisible( false );
            mkey1.setVisible( true );
          
            break;
            
            case 3:
            hangtool.setVisible(true); 
            happy7tiger.setVisible(false);
            boyandbearhappy.setVisible(false);
            ltrABC.setVisible(false);
            happy6.setVisible(false);
            boy2.setVisible( true ); 
            boy1.setVisible( false ); 
           
            break;
            
            case 4:
            hangtool.setVisible(true);
            happy6.setVisible(false);
            happy7tiger.setVisible(false);
            boyandbearhappy.setVisible(false);
            ltrABC.setVisible(false);
            mkey1.setVisible( false );
            mkey2.setVisible( true );
          
            break;
            
            case 5:
            boy2.setVisible( false );
            happy6.setVisible(false);
            happy7tiger.setVisible(false);
            boyandbearhappy.setVisible(false);
            ltrABC.setVisible(false);
            boy3.setVisible( true ); 
      
            break;

            case 6:
            hangtool.setVisible(true); 
            happy6.setVisible(false);
            happy7tiger.setVisible(false);
            boyandbearhappy.setVisible(false);
            ltrABC.setVisible(false);
            boy3.setVisible( false );
            beforehang1.setVisible( true );
          
            break;
            
            case 7:
            hangtool.setVisible(true); 
            happy6.setVisible(false);
            happy7tiger.setVisible(false);
            boyandbearhappy.setVisible(false);
            ltrABC.setVisible(false);
            mkeydead.setVisible( true );
          
            break;
            
            case 8:
            hangtool.setVisible(true); 
            happy6.setVisible(false);
            happy7tiger.setVisible(false);
            boyandbearhappy.setVisible(false);
            ltrABC.setVisible(false);
            lionsadlbl.setVisible(true);
            happy6.setVisible(false);
            beforehang1.setVisible( false );    
            deadfacelbl.setVisible( true );
            deadbodylbl.setVisible( true );
            mkeydead.setVisible( true );
          
            break;
            
            case 9:
            inputLetter.setVisible( false );
            Hmanworkspace.remove(tryLetter);      // remove the button when the game is over
            enteraltrlbl.setVisible( false );   
            hangtool.setVisible(true);
            loseback.setVisible(true);
            cloud2.setVisible(true);
            clouds1.setVisible(true);
            break;

        }
    }//GEN-LAST:event_tryLetterActionPerformed

    private void inputLetterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputLetterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputLetterActionPerformed
public static String getRandom(String[] array) {
        int random = new Random().nextInt(array.length);
        return array[random];
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HangManGame().setVisible(true);
            }
        });
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Hmanworkspace;
    private javax.swing.JLabel atmptBIrdlbl;
    private javax.swing.JLabel beforehang1;
    private javax.swing.JLabel boardlbl;
    private javax.swing.JLabel boy1;
    private javax.swing.JLabel boy2;
    private javax.swing.JLabel boy3;
    private javax.swing.JLabel boyandbearhappy;
    private javax.swing.JLabel char1;
    private javax.swing.JLabel char10;
    private javax.swing.JLabel char2;
    private javax.swing.JLabel char3;
    private javax.swing.JLabel char4;
    private javax.swing.JLabel char5;
    private javax.swing.JLabel char6;
    private javax.swing.JLabel char7;
    private javax.swing.JLabel char8;
    private javax.swing.JLabel char9;
    private javax.swing.JLabel cloud2;
    private javax.swing.JLabel cloudlbl01;
    private javax.swing.JLabel cloudlbl02;
    private javax.swing.JLabel clouds1;
    private javax.swing.JLabel deadbodylbl;
    private javax.swing.JLabel deadfacelbl;
    private javax.swing.JLabel enteraltrlbl;
    private javax.swing.JLabel gameoverlbl;
    private javax.swing.JButton hangPicture;
    private javax.swing.JLabel hangtool;
    private javax.swing.JLabel happy6;
    private javax.swing.JLabel happy7tiger;
    private javax.swing.JTextField inputLetter;
    private javax.swing.JLabel lionsadlbl;
    private javax.swing.JLabel loseback;
    private javax.swing.JLabel ltrABC;
    private javax.swing.JLabel mkey1;
    private javax.swing.JLabel mkey2;
    private javax.swing.JLabel mkeydead;
    private javax.swing.JLabel mkeymid;
    private javax.swing.JLabel snakelbl;
    private javax.swing.JButton tryLetter;
    private javax.swing.JLabel workspacelbl;
    private javax.swing.JLabel wrongGuesses;
    // End of variables declaration//GEN-END:variables
     
}
