package HangManGame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dilum De Silva
 */
public class losepage extends javax.swing.JFrame {

    /**
     * Creates new form losepage
     */
    public losepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rfeshbtn = new javax.swing.JButton();
        rfreshlbl = new javax.swing.JLabel();
        close = new javax.swing.JButton();
        closelbl = new javax.swing.JLabel();
        cloud2 = new javax.swing.JLabel();
        clouds1 = new javax.swing.JLabel();
        loseback = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1144, 665));
        setMinimumSize(new java.awt.Dimension(1144, 665));
        setPreferredSize(new java.awt.Dimension(1144, 665));
        setResizable(false);
        setSize(new java.awt.Dimension(1144, 665));
        getContentPane().setLayout(null);

        rfeshbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangManGame/refresh2.png"))); // NOI18N
        rfeshbtn.setContentAreaFilled(false);
        rfeshbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfeshbtnActionPerformed(evt);
            }
        });
        getContentPane().add(rfeshbtn);
        rfeshbtn.setBounds(830, 110, 80, 80);

        rfreshlbl.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        rfreshlbl.setText("Refresh");
        getContentPane().add(rfreshlbl);
        rfreshlbl.setBounds(830, 90, 80, 22);

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangManGame/close3.png"))); // NOI18N
        close.setContentAreaFilled(false);
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close);
        close.setBounds(950, 60, 100, 120);

        closelbl.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        closelbl.setText("Exit");
        getContentPane().add(closelbl);
        closelbl.setBounds(960, 90, 50, 22);

        cloud2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangManGame/cloud2.png"))); // NOI18N
        getContentPane().add(cloud2);
        cloud2.setBounds(690, 10, 430, 230);

        clouds1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangManGame/clouds1.png"))); // NOI18N
        getContentPane().add(clouds1);
        clouds1.setBounds(480, -10, 500, 278);

        loseback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangManGame/rsz_lose1.png"))); // NOI18N
        loseback.setMaximumSize(new java.awt.Dimension(1200, 674));
        loseback.setMinimumSize(new java.awt.Dimension(1200, 674));
        loseback.setPreferredSize(new java.awt.Dimension(1200, 674));
        getContentPane().add(loseback);
        loseback.setBounds(0, -150, 1680, 970);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rfeshbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfeshbtnActionPerformed
         // this btn will close the current window and will take you to start page of the game
         dispose(); 
         startframe Main=new  startframe();
         Main.setVisible(true);
    }//GEN-LAST:event_rfeshbtnActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
         dispose(); 
    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(losepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(losepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(losepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(losepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new losepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JLabel closelbl;
    private javax.swing.JLabel cloud2;
    private javax.swing.JLabel clouds1;
    private javax.swing.JLabel loseback;
    private javax.swing.JButton rfeshbtn;
    private javax.swing.JLabel rfreshlbl;
    // End of variables declaration//GEN-END:variables
}
