/*
 * Progaramming Priciples 01 (Course Work - 2 )
 * Student Name - Dilum Maduranga De Silva
 * UoW ID       - 16266371 (W1626637)
 * IIT ID       - 2016142  
 */
package HangManGame;

/**
 *
 * @author Dilum De Silva
 */
public class winJframe extends javax.swing.JFrame {

    /**
     * Creates new form winJframe
     */
    public winJframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        restartmsg = new javax.swing.JLabel();
        restartbtn = new javax.swing.JButton();
        closemsg = new javax.swing.JLabel();
        closebtn = new javax.swing.JButton();
        winback = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1144, 665));
        setMinimumSize(new java.awt.Dimension(1144, 665));
        setPreferredSize(new java.awt.Dimension(1144, 665));
        setResizable(false);
        setSize(new java.awt.Dimension(1144, 665));
        getContentPane().setLayout(null);

        restartmsg.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        restartmsg.setForeground(new java.awt.Color(255, 255, 255));
        restartmsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        restartmsg.setText("Restart");
        getContentPane().add(restartmsg);
        restartmsg.setBounds(820, 450, 60, 17);

        restartbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangManGame/refresh2.png"))); // NOI18N
        restartbtn.setBorderPainted(false);
        restartbtn.setContentAreaFilled(false);
        restartbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartbtnActionPerformed(evt);
            }
        });
        getContentPane().add(restartbtn);
        restartbtn.setBounds(760, 350, 190, 150);

        closemsg.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        closemsg.setForeground(new java.awt.Color(255, 255, 255));
        closemsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closemsg.setText("Exit");
        getContentPane().add(closemsg);
        closemsg.setBounds(1040, 430, 60, 50);

        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangManGame/close3.png"))); // NOI18N
        closebtn.setBorderPainted(false);
        closebtn.setContentAreaFilled(false);
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });
        getContentPane().add(closebtn);
        closebtn.setBounds(1030, 340, 120, 100);

        winback.setIcon(new javax.swing.ImageIcon("F:\\HangMan(My)\\Hangman pics\\wincoverfinal.png")); // NOI18N
        winback.setMaximumSize(new java.awt.Dimension(1200, 674));
        winback.setMinimumSize(new java.awt.Dimension(1200, 674));
        winback.setPreferredSize(new java.awt.Dimension(1200, 674));
        getContentPane().add(winback);
        winback.setBounds(0, -170, 1680, 970);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
              // this will terminate entire game
               dispose();
    }//GEN-LAST:event_closebtnActionPerformed

    private void restartbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartbtnActionPerformed
         // restart button: this will close winjframe and restart the game   
            dispose(); 
            startframe hMan=new  startframe();
            hMan.setVisible(true);
       
    }//GEN-LAST:event_restartbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(winJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(winJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(winJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(winJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new winJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closebtn;
    private javax.swing.JLabel closemsg;
    private javax.swing.JButton restartbtn;
    private javax.swing.JLabel restartmsg;
    private javax.swing.JLabel winback;
    // End of variables declaration//GEN-END:variables
}
